### ISSUE TITLE
Could you also provide perspective map for WorldExpo and UCF_CC_50?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [miao0913/PACNN-PerspectiveAware-CrowdCounting#2]
The paper says that WorldExpo has provided ground truth perspective map, however, I cannot find any corresponding annotations.
It would be great if you can provide perspective map of these two datasets.

**Comment by miao0913** [comment]
Hi, I do not think it is legitimately right for us to public their data. 
If you want the perspective map of WorldExpo dataset, I would suggest to contact the authors first. 
Thanks  !

**Comment by Naruto-Sasuke** [comment]
Thank you for your relay. In fact, I am try to reimplement your paper via pytorch.  I normalize my data to 0~1.    I need to normalize perspective map to 0-1, right? However,  by which normalization method?

**Comment by miao0913** [comment]
you can normalize it by x-min(x)/max(x) - min(x) for ShanghaiTech PartA
