### ISSUE TITLE
The 'mat' data version is different of training sets(v7.3) and test sets(v5.0).

### ISSUE THREAD

**Issue by Naruto-Sasuke** [miao0913/PACNN-PerspectiveAware-CrowdCounting#5]
I found that the mat version of  Shanghai A training is v7.3, while the test sets are version of '5.0'.
As I am using python, I found the version gap makes trouble when loading data.
The former version of data cannot not be loaded by 'scipy.io.loadmat' and we have to use 'h5py.File' to load it.
However, the latter one should be loaded by 'spicy.io.loadmat', or will get a 'signature  error'.

It would be nice, if the data version is consistent.
Thank you.

**Comment by Naruto-Sasuke** [comment]
Perspective map of SHB is totally version v7.3.

**Comment by miao0913** [comment]
I was away from work. And I believe you can do it by yourself. So I do not bother to do it.
